import { useEffect, useState } from "react";
import Head from "next/head";

import Results from "../components/Results";
import requests from "../../utils/requests";
import Nav from "@/components/Nav";

export default function Home(props) {
  const [allData, setAllData] = useState();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const genre = props?.query?.genre || "fetchTrending";
        const request = await fetch(
          `https://api.themoviedb.org/3${requests[genre]?.url}`
        ).then((res) => {
          return res.json();
        });

        setAllData(request?.results);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, [props?.query?.genre]);

  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Nav */}
      <Nav />

      {/* Results */}
      {allData?.length > 0 && <Results results={allData} />}
    </>
  );
}

export async function getServerSideProps(context) {
  const { query } = context;
  const path = context.req.url;

  return {
    props: {
      query, // Pass the query parameters as a prop
      path, // Pass the path as a prop
    },
  };
}
